version: '3.1'
services:
  postgres:
    image: postgres:12.6
    container_name: postgres
    network_mode: 'host'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q1w2e3
      POSTGRES_DB: hackathon
